"""remove unnecessary timestamps

Revision ID: 200c1eafc93b
Revises: 56b29d453a92
Create Date: 2025-10-02 18:48:40.682463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '200c1eafc93b'
down_revision: Union[str, None] = '56b29d453a92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_permissions', 'granted_at')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_index('ix_usage_logs_timestamp', table_name='usage_logs')
    op.drop_index('idx_usage_user_time', table_name='usage_logs')
    op.create_index('idx_usage_user_time', 'usage_logs', ['user_id', 'created_at'], unique=False)
    op.drop_constraint('uq_usage_log', 'usage_logs', type_='unique')
    op.create_unique_constraint('uq_usage_log', 'usage_logs', ['user_id', 'created_at', 'service_type'])
    op.create_index(op.f('ix_usage_logs_created_at'), 'usage_logs', ['created_at'], unique=False)
    op.drop_column('usage_logs', 'updated_at')
    op.drop_column('usage_logs', 'timestamp')
    op.drop_column('user_roles', 'assigned_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('usage_logs', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('usage_logs', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_usage_logs_created_at'), table_name='usage_logs')
    op.drop_constraint('uq_usage_log', 'usage_logs', type_='unique')
    op.create_unique_constraint('uq_usage_log', 'usage_logs', ['user_id', 'timestamp', 'service_type'])
    op.drop_index('idx_usage_user_time', table_name='usage_logs')
    op.create_index('idx_usage_user_time', 'usage_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index('ix_usage_logs_timestamp', 'usage_logs', ['timestamp'], unique=False)
    op.add_column('roles', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('role_permissions', sa.Column('granted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
