"""create_activity_watch_tokens_table

Revision ID: d26cd4811e34
Revises: 9c7e8cba487b
Create Date: 2025-11-11 10:35:49.878035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd26cd4811e34'
down_revision: Union[str, None] = '9c7e8cba487b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_watch_tokens',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_activity_watch_tokens_token_hash', 'activity_watch_tokens', ['token_hash'], unique=False)
    op.create_index('idx_activity_watch_tokens_user_id', 'activity_watch_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_activity_watch_tokens_token_hash'), 'activity_watch_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_activity_watch_tokens_user_id'), 'activity_watch_tokens', ['user_id'], unique=True)
    op.create_unique_constraint(None, 'blacklisted_tokens', ['id'])
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'refresh_tokens', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_constraint(None, 'blacklisted_tokens', type_='unique')
    op.drop_index(op.f('ix_activity_watch_tokens_user_id'), table_name='activity_watch_tokens')
    op.drop_index(op.f('ix_activity_watch_tokens_token_hash'), table_name='activity_watch_tokens')
    op.drop_index('idx_activity_watch_tokens_user_id', table_name='activity_watch_tokens')
    op.drop_index('idx_activity_watch_tokens_token_hash', table_name='activity_watch_tokens')
    op.drop_table('activity_watch_tokens')
    # ### end Alembic commands ###
