"""add usage_logs table

Revision ID: 1ef5772e58f8
Revises: c2a7fc1f1a3e
Create Date: 2025-10-02 14:44:22.203449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef5772e58f8'
down_revision: Union[str, None] = 'c2a7fc1f1a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql

    op.create_table('usage_logs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('service_type', sa.String(length=50), nullable=False),
        sa.Column('tokens_used', sa.Integer(), nullable=False),
        sa.Column('processing_time', sa.Float(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('user_id', 'timestamp', 'service_type', name='uq_usage_log')
    )
    op.create_index('idx_usage_service_type', 'usage_logs', ['service_type'], unique=False)
    op.create_index('idx_usage_user_time', 'usage_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_usage_logs_service_type'), 'usage_logs', ['service_type'], unique=False)
    op.create_index(op.f('ix_usage_logs_timestamp'), 'usage_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_timestamp'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_service_type'), table_name='usage_logs')
    op.drop_index('idx_usage_user_time', table_name='usage_logs')
    op.drop_index('idx_usage_service_type', table_name='usage_logs')
    op.drop_table('usage_logs')
    # ### end Alembic commands ###
