"""remove timestamps from permissions table

Revision ID: 56b29d453a92
Revises: 6e586bff5aad
Create Date: 2025-10-02 18:42:30.835778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56b29d453a92'
down_revision: Union[str, None] = '6e586bff5aad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'created_at')
    op.drop_column('permissions', 'updated_at')
    op.create_unique_constraint(None, 'usage_logs', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_logs', type_='unique')
    op.add_column('permissions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('permissions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
