"""create_blacklisted_tokens_table

Revision ID: 9c7e8cba487b
Revises: 2be9725677cc
Create Date: 2025-10-24 17:11:51.219257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9c7e8cba487b'
down_revision: Union[str, None] = '2be9725677cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('idx_blacklisted_tokens_expires_at', 'blacklisted_tokens', ['expires_at'], unique=False)
    op.create_index('idx_blacklisted_tokens_token_hash', 'blacklisted_tokens', ['token_hash'], unique=False)
    op.create_index('idx_blacklisted_tokens_user_id', 'blacklisted_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_blacklisted_tokens_token_hash'), 'blacklisted_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_blacklisted_tokens_user_id'), 'blacklisted_tokens', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'organizations', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_index(op.f('ix_blacklisted_tokens_user_id'), table_name='blacklisted_tokens')
    op.drop_index(op.f('ix_blacklisted_tokens_token_hash'), table_name='blacklisted_tokens')
    op.drop_index('idx_blacklisted_tokens_user_id', table_name='blacklisted_tokens')
    op.drop_index('idx_blacklisted_tokens_token_hash', table_name='blacklisted_tokens')
    op.drop_index('idx_blacklisted_tokens_expires_at', table_name='blacklisted_tokens')
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
