"""add organization_id to user_roles table

Revision ID: 99740f35a284
Revises: 610dbcc81c5e
Create Date: 2025-10-06 12:51:35.896777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '99740f35a284'
down_revision: Union[str, None] = '610dbcc81c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_user_roles_organization_id'), 'user_roles', ['organization_id'], unique=False)
    op.create_foreign_key('fk_user_roles_organization_id', 'user_roles', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_roles_organization_id', 'user_roles', type_='foreignkey')
    op.drop_index(op.f('ix_user_roles_organization_id'), table_name='user_roles')
    op.drop_column('user_roles', 'organization_id')
    # ### end Alembic commands ###
