"""add_organization_type_and_size

Revision ID: 56396527e403
Revises: baec521e372c
Create Date: 2026-01-25 20:37:09.564111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56396527e403'
down_revision: Union[str, None] = 'baec521e372c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add organization_type and organization_size fields
    op.add_column('organizations', sa.Column('organization_type', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('organization_size', sa.String(length=20), nullable=True))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invitations_token_key', 'invitations', type_='unique')
    op.drop_index('ix_invitations_token', table_name='invitations')
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_unique_constraint(None, 'invitations', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invitations', type_='unique')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.create_index('ix_invitations_token', 'invitations', ['token'], unique=False)
    op.create_unique_constraint('invitations_token_key', 'invitations', ['token'])
    # ### end Alembic commands ###

    # Drop organization fields
    op.drop_column('organizations', 'organization_size')
    op.drop_column('organizations', 'organization_type')
