"""add_invitations_table

Revision ID: baec521e372c
Revises: a1b2c3d4e5f6
Create Date: 2026-01-25 19:15:24.794430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'baec521e372c'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create invitations table
    op.create_table(
        'invitations',
        sa.Column('id', UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('organization_id', UUID(), nullable=False),
        sa.Column('invited_by_user_id', UUID(), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False, server_default='member'),
        sa.Column('token', sa.String(length=255), nullable=False),
        sa.Column('status', sa.Enum('pending', 'accepted', 'expired', 'revoked', name='invitationstatus'), nullable=False, server_default='pending'),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('accepted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token')
    )

    # Create indexes
    op.create_index('ix_invitations_email', 'invitations', ['email'])
    op.create_index('ix_invitations_organization_id', 'invitations', ['organization_id'])
    op.create_index('ix_invitations_status', 'invitations', ['status'])
    op.create_index('ix_invitations_token', 'invitations', ['token'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activity_watch_tokens', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_watch_tokens', type_='unique')
    # ### end Alembic commands ###

    # Drop indexes
    op.drop_index('ix_invitations_token', 'invitations')
    op.drop_index('ix_invitations_status', 'invitations')
    op.drop_index('ix_invitations_organization_id', 'invitations')
    op.drop_index('ix_invitations_email', 'invitations')

    # Drop table
    op.drop_table('invitations')

    # Drop enum type
    op.execute('DROP TYPE invitationstatus')
